### ISSUE TITLE
If done in the way your SwiftUI Example suggests, plugins will be added repeatedly. 

### ISSUE THREAD

**Issue by AnthonyHarveyRapptrLabs** [segment-integrations/analytics-swift-firebase#11]
I implemented the code shown in your SwiftUI example and the add(plugin: ) was called every time a any main.track was called.
Then for every plugin added (the same plugin over & over in this case), each life cycle event would be called that many more times per actual event. It was quite  a mess.

instead I used: 
```
import Foundation
import Segment
import SegmentFirebase

extension Analytics {
    enum Constants {
        static let writeKey = "pvCQtnvudI9qAFYZKAxEQF4fvtuAlCws"
    }
    static let main = Analytics(configuration:Configuration(writeKey: Constants.writeKey).flushAt(3).trackApplicationLifecycleEvents(true))
}
```

and added the plugin in `applicationDidFinishLaunching` like this:

` Analytics.main.add(plugin: FirebaseDestination())`

**Comment by bsneed** [comment]
Maybe this is old and was addressed at some point, the sample app looks fine.  Please reopen if necessary.
