### ISSUE TITLE
Allow FIROption to be passed into plugin

### ISSUE THREAD

**Issue by stephengilroy-grx** [segment-integrations/analytics-swift-firebase#17]
Hey segment team!

Feature request here. We would like to send our analytics to a firebase dev environment to keep our prod analytics clean. Unfortunately the only way to do this is via passing in a `FIROption` object into the Firebase configure call as suggested here: https://firebase.google.com/docs/projects/multiprojects

How would we feel adding an optional initializer in the `FirebaseDestination` like: `init(_ option: FIROption? = nil)`? It leaks Firebase types into the caller but perhaps that's fine as the caller is having the Firebase SDK pulled in regardless? Alternatively we could have something with primitives like `init(_ configPath: String? = nil)` and the `FirebaseDestination` could construct the `FIROption` object for us?

Thoughts?

**Comment by bsneed** [comment]
Having the FIROption as a param sounds fine to me.  Shouldn't be an issue as the firebase SDK would already be present.  If you can make a PR, I can probably merge it in pretty quickly.  Lemme know.  Thanks!!

**Comment by stephengilroy-grx** [comment]
Will do! Thanks @bsneed

**Comment by mattiosdev** [comment]
@bsneed PR is ready. Please take a look. Thank you.

**Comment by bsneed** [comment]
Thanks @mattiosdev and @stephengilroy-grx !  Just released as 1.2.0.
