### ISSUE TITLE
Add support for Firebase 9.X

### ISSUE THREAD

**Issue by tristan-reveri** [segment-integrations/analytics-swift-firebase#2]
Firebase 9.0 added some major new features that we want to migrate to, however our current dependency on SegmentFirebase is blocking our migration.

Do you have adding support on the roadmap? or is it something we can do as consumers?

**Comment by tristan-reveri** [comment]
I've got a dozen other fires to put out before I'll have the time to do this, so if I can just get it on your roadmap that would be great.

If the need becomes more pressing (it's currently blocking us adopting Swift Codable Firestore) I'll do this and raise a PR.

**Comment by tristan-reveri** [comment]
Hey @bsneed, [here's a PR](https://github.com/segment-integrations/analytics-swift-firebase/pull/3) updating to the latest release 9.1.0.

There was only one change required, around a deprecated key name.

**Comment by tristan-reveri** [comment]
Note, I've only made it compile. I haven't tried integrating it.

**Comment by bsneed** [comment]
Ok, thanks @tristan-reveri ! 

I'll get this on our to-do docket for this coming week.
