### ISSUE TITLE
Identify call doesn't associate Firebase user with Crashlytics

### ISSUE THREAD

**Issue by tristan-warner-smith** [segment-integrations/analytics-swift-firebase#5]
The current implementation is:
`Analytics.setUserID("SomeUserId")`

However for Crashlytics to correctly associate crashes with a firebase user you also need to call:
`Crashlytics.crashlytics().setUserID("SomeUserId")`

You can repro this by:
1. Calling `.identify(userID, traits: ["email": email])`
2. Triggering a crash
3. Checking the `Data` tab on Crashlytics for the crash event and noting a lack of `User.Id`

If you set the Crashlytics User Id correctly you'll see the user section shown here (for Android)
<img width="931" alt="Screenshot 2022-10-05 at 10 33 25" src="https://user-images.githubusercontent.com/102950712/194029294-0c711136-6202-4819-bd92-46e093b45727.png">

**Comment by bsneed** [comment]
Closing due to age.  Please reopen if this is still an issue.
