### ISSUE TITLE
Data not sent through to firebase

### ISSUE THREAD

**Issue by yucelHap** [segment-integrations/analytics-swift-firebase#6]
I've followed the steps as stated, and also have the application registered in firebase. I've also got the googleService-info.plist file in the project (I know it works as I can send data to firebase). 

However, upon running my code I do not see any analytics data sent to firebase (checked firebase analytics dashboard). I'm confused with what the issue is as no error has been thrown when compiling or running.

**Comment by bsneed** [comment]
Please reach out to Segment support.
