### ISSUE TITLE
Unable to add package 

### ISSUE THREAD

**Issue by krishVenkat11** [segment-integrations/analytics-swift-firebase#7]
Hey , I am not able to add the package via SPM , the package is not being resolved and therefore as a result it is damaging my other packages! Anyway to resolve this issue ?

<img width="645" alt="screen_shot_2022-12-08_at_4 44 40_pm" src="https://user-images.githubusercontent.com/116249250/206464136-26f7f334-ae8a-4267-9142-e3199ded11c6.png">

**Comment by bsneed** [comment]
Not a segment issue.  Complain to Xcode. :(
