### ISSUE TITLE
SegmentFirebase won't build in macOS project - incompatible minimum macOS version with Segment SDK

### ISSUE THREAD

**Issue by Christine-Hostage-Bose** [segment-integrations/analytics-swift-firebase#8]
I created a fresh macOS project and added one package dependency: 'SegmentFirebase' for '1.0.0 - Next Major'. All the packages were installed including: 
Segment v1.3.3
SegmentFirebase v1.1.4

Building fails with the error:
SegmentFirebase 1 issue
  The package product 'Segment' requires minimum platform version 10.15 for the macOS platform, but this target supports 10.13.

**Comment by bsneed** [comment]
Fixed on master, release coming shortly.
